# SOPS configuration file
# This file defines encryption keys and rules for secret files

keys:
  - &admin_daniel age17e93e9u5zwlm322y3jy4wduze4lyawcz2f4d9jt4xqpx66u9td4s8hrk39

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_daniel
